plugins {
    id 'java'
    id 'io.qameta.allure' version '4.1.0'
}

group = 'kz.kaspi'
version = '1.0-SNAPSHOT'

repositories {
    mavenCentral()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.2')
    testImplementation 'org.junit.jupiter:junit-jupiter'
    testImplementation 'com.codeborne:selenide:7.2.1'
    testImplementation 'io.qameta.allure:allure-junit5:2.25.0'
    testImplementation 'io.qameta.allure:allure-selenide:2.25.0'

    testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
    testImplementation 'org.slf4j:slf4j-simple:2.0.12'
}

allure {
    version = "2.25.0"
    adapter {
        frameworks {
            junit5 {
                enabled = true
            }
        }
    }
}

compileTestJava {
    options.encoding = 'UTF-8'
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}

tasks.withType(Test) {
    useJUnitPlatform()
    ignoreFailures = true

    systemProperties(System.getProperties())
    testLogging {
        lifecycle {
            events "started", "skipped", "failed", "standard_error", "standard_out"
            exceptionFormat "short"
        }
    }
}